name: Run Python Unittest with Coverage

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'


    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --junitxml=pytest-results.xml

    - name: Upload pytest JUnit XML results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-junit-results
        path: pytest-results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      with:
        junit_files: pytest-results.xml

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/

    - name: Upload coverage XML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml-report
        path: coverage.xml

    - name: Display coverage summary in workflow
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: false
        format: markdown
        output: both
